//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleaningApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbcleaningEntities : DbContext
    {
        public dbcleaningEntities()
            : base("name=dbcleaningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbBathroom> tbBathrooms { get; set; }
        public virtual DbSet<tbBedroom> tbBedrooms { get; set; }
        public virtual DbSet<tbcategory> tbcategories { get; set; }
        public virtual DbSet<tbCeiling> tbCeilings { get; set; }
        public virtual DbSet<tbExtra> tbExtras { get; set; }
        public virtual DbSet<tbGarage> tbGarages { get; set; }
        public virtual DbSet<tbOven> tbOvens { get; set; }
        public virtual DbSet<tbreview> tbreviews { get; set; }
        public virtual DbSet<tbservice> tbservices { get; set; }
        public virtual DbSet<tbStaff> tbStaffs { get; set; }
        public virtual DbSet<tbWindow> tbWindows { get; set; }
        public virtual DbSet<tbbooking> tbbookings { get; set; }
        public virtual DbSet<tbPanel> tbPanels { get; set; }
    }
}
