//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleaningApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbbooking
    {
        public string custAddress { get; set; }
        public string custName { get; set; }
        public string custPhoneNo { get; set; }
        public string custEmail { get; set; }
        public System.DateTime ddate { get; set; }
        public System.TimeSpan ttime { get; set; }
        public Nullable<int> categoryid { get; set; }
        public Nullable<int> serviceid { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
    
        public virtual tbcategory tbcategory { get; set; }
        public virtual tbservice tbservice { get; set; }
    }
}
