//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleaningApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbcategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbcategory()
        {
            this.tbbookings = new HashSet<tbbooking>();
            this.tbservices = new HashSet<tbservice>();
        }
    
        public int categoryid { get; set; }
        public string categoryName { get; set; }
        public string categoryPhoto { get; set; }
        public string categoryDesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbbooking> tbbookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbservice> tbservices { get; set; }
    }
}
