//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleaningApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPanel
    {
        public string companyName { get; set; }
        public string phoneNo { get; set; }
        public string companyAddress { get; set; }
        public string timings { get; set; }
        public string aboutUs { get; set; }
        public string companyEmail { get; set; }
        public string logo { get; set; }
    }
}
