//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleaningApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbreview
    {
        public int reviewid { get; set; }
        public string customerName { get; set; }
        public string heading { get; set; }
        public string review { get; set; }
        public int stars { get; set; }
    }
}
