//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleaningApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbStaff
    {
        public int staffId { get; set; }
        public string fullname { get; set; }
        public string staffAddress { get; set; }
        public Nullable<int> phoneNo { get; set; }
        public string emailid { get; set; }
        public string position { get; set; }
        public string photo { get; set; }
    }
}
